<?php

use Illuminate\Database\Seeder;

class players extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        \Illuminate\Support\Facades\DB::statement('INSERT INTO `teams` (`id`, `team_name`, `isdelete`, `logo`, `created_at`, `updated_at`) VALUES
(1, \'DB Strikers\', NULL, \'dbstrikers.jpg\', NULL, NULL),
(2, \'Navi Mumbai Eagles\', NULL, \'eagels.jpg\', NULL, NULL),
(3, \'Dombivli Dorcays\', NULL, \'dombivali.jpg\', NULL, NULL),
(4, \'Andheri Supernaturals\', NULL, \'andheri.jpg\', NULL, NULL),
(5, \'Kodial Super Kings\', NULL, \'kodial.jpg\', NULL, NULL),
(6, \'Shivaji Park Tigers\', NULL, \'tigers.jpg\', NULL, NULL),
(7, \'Karwar Karavali Kings\', NULL, \'karwar.jpg\', NULL, NULL),
(8, \'Thane Titans\', NULL, \'titans.jpg\', NULL, NULL),
(9, \'King Circle Knight Riders\', NULL, \'riders.jpg\', NULL, NULL)');

        \Illuminate\Support\Facades\DB::statement('INSERT INTO `players` (`id`, `player_name`, `photo`, `team_id`, `created_at`, `updated_at`, `is_delete`, `player_param`, `enable_voting`, `is_playing`) VALUES
(1, \'Aaditya Naik\', \'https://drive.google.com/uc?id=1ycal2vNOYwj6oujQaI2l6vdXFp1b82QD\', 6, NULL, NULL, NULL, 1, NULL, NULL),
(2, \'ABHAY KAMAT\', \'https://drive.google.com/uc?id=1piB8CIShRr5TD5iH522MyUBGKpPv9Whr\', 7, NULL, NULL, NULL, 3, NULL, NULL),
(3, \'Abhishek Bhat\', \'https://drive.google.com/uc?id=1468N8PXZ8g_pBSnSW_ULN4K7Wv1KIV-R\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(4, \'Aditya Pai\', \'https://drive.google.com/uc?id=1zXwHi9cFmkwZ6uOiwIbilziUxm7JRBZg\', 9, NULL, NULL, NULL, 3, NULL, NULL),
(5, \'Aditya  Sakhardande \', \'https://drive.google.com/uc?id=1_Aqu3G5RVWigzqs4pdanNkqffdhn47Fv\', 9, NULL, NULL, NULL, 3, NULL, NULL),
(6, \'Aditya  Kudva\', \'https://drive.google.com/uc?id=1wVbfNKvp3Pa4nJBhJUhuKznp8vRDmxI5\', 2, NULL, NULL, NULL, 3, NULL, 1),
(7, \'Ajay Kamat\', \'https://drive.google.com/uc?id=1eKNo2ZTNpLXQTEQSezZnYrAKPdpat0YO\', 7, NULL, NULL, NULL, 1, NULL, NULL),
(8, \'Ajith  Bhat \', \'https://drive.google.com/uc?id=14jzED8vXg_we7ES8Xyh_nOdIwlKEupau\', 1, NULL, NULL, NULL, 3, NULL, 1),
(9, \'akshay kamat\', \'https://drive.google.com/uc?id=18QtFY7xudcnW8TVqrQd6bE1H5z2X1ZVI\', 9, NULL, NULL, NULL, 3, NULL, NULL),
(10, \'Ameya Pai\', \'https://drive.google.com/uc?id=1g2TX16wDjQorhhxYfeJR7mw7dlwd4oI7\', 9, NULL, NULL, NULL, 1, NULL, NULL),
(11, \'Ameya  Aras\', \'https://drive.google.com/uc?id=1Ir0YdutEZjEW9G-7q7vWx5BMXdMToF0L\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(12, \'Amit Prabhu\', \'https://drive.google.com/uc?id=1fBKxD67mbw1uc1_V0uVJswsoxG3iCrTY\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(13, \'Amit  Shenoy\', \'https://drive.google.com/uc?id=1i8H5Ice6GeRRIs7cf5w5CmAaqfxoyBWc\', 1, NULL, NULL, NULL, 3, NULL, 1),
(14, \'AMIT  SHENOY\', \'https://drive.google.com/uc?id=1U-6Di_ZSr-ufZnRG7mH_GJpT3NSYPZMs\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(15, \'Amogh Bhatkal\', \'https://drive.google.com/uc?id=17FPpXEuso2zCIRJRs4bt3FwfKQb68kjq\', 3, NULL, NULL, NULL, 3, NULL, NULL),
(16, \'Ananth Shenoy\', \'https://drive.google.com/uc?id=1hVcv9KJecAMDh9w7ugak5_f9fQQ478UY\', 1, NULL, NULL, NULL, 3, NULL, 1),
(17, \'Ananth ray Pai\', \'https://drive.google.com/uc?id=1MpDQoX-Rz6X_io5KUU3O0zfd1a2HMO7w\', 2, NULL, NULL, NULL, 3, NULL, 1),
(18, \'Ananthesh Pai\', \'https://drive.google.com/uc?id=1_DtO-wOy0rjWc8tzmM6UrNgoObFeUT0p\', 2, NULL, NULL, NULL, 3, NULL, 1),
(19, \'Aneesh Kamath\', \'https://drive.google.com/uc?id=14ftfGc9-XX7Q29wGrhyCleTTwNjRAY1X\', 6, NULL, NULL, NULL, 3, NULL, NULL),
(20, \'Anjan Shanbhag\', \'https://drive.google.com/uc?id=1OWhs8Odf_plRYSXgqZxe-LbgQpjqqUTf\', 3, NULL, NULL, NULL, 1, NULL, NULL),
(21, \'Arjun  Bhat \', \'https://drive.google.com/uc?id=1sS2mFUfUKt-QtTEwi45e_3YWTCy0Ssjd\', 1, NULL, NULL, NULL, 1, NULL, 1),
(22, \'Ashish Kamath\', \'https://drive.google.com/uc?id=1G1uqEPK0CHaN10pNohkqtPWqoi9hTslj\', 1, NULL, NULL, NULL, 1, NULL, 1),
(23, \'Ashwath Pai\', \'https://drive.google.com/uc?id=1KDo4x2QZQmBBIjOyHrv_O7evmq94YUQs\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(24, \'Ashwin Pai\', \'https://drive.google.com/uc?id=1V_FnxFGRvIsmcdsC-ghYXEm3O3R16AR2\', 1, NULL, NULL, NULL, 3, NULL, 1),
(25, \'Atharva Pai\', \'https://drive.google.com/uc?id=1JDXb9iamIEU83I88Y-XIiGt1GvJfF3za\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(26, \'Athul Shenoy\', \'https://drive.google.com/uc?id=1DdserXjLqE4UuXIoVKP_uPdl8dMOPt_f\', 1, NULL, NULL, NULL, 1, NULL, 1),
(27, \'Atul Prabhu\', \'https://drive.google.com/uc?id=1IxbiLzgO3KMppebiCVs9RTjBZJ9xpf6y\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(28, \'Avinash Kamath\', \'https://drive.google.com/uc?id=1O8RfXXI4J4AGmDe1i_G5kv5D9_5HvyqO\', 3, NULL, NULL, NULL, 3, NULL, NULL),
(29, \'avirat kamat\', \'https://drive.google.com/uc?id=1MzMu-aokJ8sGi6OZq-6NST1JfPCU6V2M\', 3, NULL, NULL, NULL, 3, NULL, NULL),
(30, \'Chandrakanth Shenoy\', \'https://drive.google.com/uc?id=1CY77rmZzcJyEuSWA2d4zKODeRIEY3q6J\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(31, \'Charan  Kamath\', \'https://drive.google.com/uc?id=1dT35qcY3IVQ_fD-ZoQN6MdYnWTgMmZDr\', 2, NULL, NULL, NULL, 3, NULL, 1),
(32, \'Chirag Shenoy\', \'https://drive.google.com/uc?id=1H_BBy3K8GsxyXFkgb7z5HeA7UxuaCevO\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(33, \'Chirag  Shanbhag \', \'https://drive.google.com/uc?id=1E6GSCtOJEp9WY2cW-zk_DeWCNgSCID62\', 9, NULL, NULL, NULL, 1, NULL, NULL),
(34, \'Dayananda Pai\', \'https://drive.google.com/uc?id=1iGDG2VkJPfV2WbqgbXcmVvnyQo9-0Pfc\', 9, NULL, NULL, NULL, 1, NULL, NULL),
(35, \'Deepak Kamath\', \'https://drive.google.com/uc?id=1AAWNoEf4z8undFg3m_T_ypTIZlEgQD1T\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(36, \'Deepak H Shenoy\', \'https://drive.google.com/uc?id=1RATX_JCBn7ipXfP8FTYMe_uJKWHHwDA2\', 6, NULL, NULL, NULL, 3, NULL, NULL),
(37, \'Deepak R Nayak\', \'https://drive.google.com/uc?id=1sABwqlFUTGf9xu8ZRE0FJ4ui6fkrlcRn\', 4, NULL, NULL, NULL, 1, NULL, NULL),
(38, \'Deepesh Shenoy\', \'https://drive.google.com/uc?id=1-Qp3FoguieD6x00W6ikYuzVvRMHoCYaR\', 1, NULL, NULL, NULL, 1, NULL, 1),
(39, \'Devdas  Nayak\', \'https://drive.google.com/uc?id=1z70lDTGMoF0jaQYo1FJv1p9YkG6o5fwL\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(40, \'Dilip Kamath\', \'https://drive.google.com/uc?id=1f0YCybSieifioIlILelbw-ztishxjOS2\', 1, NULL, NULL, NULL, 3, NULL, 1),
(41, \'DURVESH  TENDOLKAR\', \'https://drive.google.com/uc?id=19j9hdyCiHj0jkuZNWM2QE3FZF-4Do6G0\', 9, NULL, NULL, NULL, 3, NULL, NULL),
(42, \'GANESH NAYAK\', \'https://drive.google.com/uc?id=1oWIRJknktM4MdizUU8PhcJg-gNGIlcbP\', 2, NULL, NULL, NULL, 3, NULL, 1),
(43, \'Gautham Pai\', \'https://drive.google.com/uc?id=1BohBILEdHjPjW7OMepxFiJ3MFavAK8Tm\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(44, \'Girish Pai.B.H\', \'https://drive.google.com/uc?id=1MBuPSmfo1oa6HqB4KOdrIw0nB4d8yaq-\', 2, NULL, NULL, NULL, 1, NULL, 1),
(45, \'Girish Shenoy\', \'https://drive.google.com/uc?id=1Rx7sT4AY9clB42OoNEM_GyzaddkKOA_v\', 7, NULL, NULL, NULL, 1, NULL, NULL),
(46, \'Girish  Pai \', \'https://drive.google.com/uc?id=1vYDtho71AaOJqcd4V0G6lIpI8ZdlUsLy\', 5, NULL, NULL, NULL, 2, NULL, NULL),
(47, \'Gurudas  Shenoy \', \'https://drive.google.com/uc?id=1gBlnznJsL3RiRVnqTqNV5lHrom1lrZVB\', 9, NULL, NULL, NULL, 3, NULL, NULL),
(48, \'H.sachin Gadiyar\', \'https://drive.google.com/uc?id=1Xd8Hxbhch1kvdYsSxf9L7R2KSSvXUmhk\', 1, NULL, NULL, NULL, 3, NULL, 1),
(49, \'Jayant Prabhu\', \'https://drive.google.com/uc?id=1xODgt5XwhG5u7KqYmzQ04nSmWyhOHD8K\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(50, \'Jeethen Nayak\', \'https://drive.google.com/uc?id=1A0rzKbaqtD3SBDEATdXOR-fworm9Zdiu\', 8, NULL, NULL, NULL, 2, NULL, NULL),
(51, \'Karthik Prabhu\', \'https://drive.google.com/uc?id=1C0ue6ZQ5ki35a3LsaQLQg5dgS5FhPfeM\', 3, NULL, NULL, NULL, 2, NULL, NULL),
(52, \'Kartik Gadiyar\', \'https://drive.google.com/uc?id=1gYkkPLcf_wNByZJfN5dW42R8gWSg869p\', 9, NULL, NULL, NULL, 3, NULL, NULL),
(53, \'Keerthan  Prabhu\', \'https://drive.google.com/uc?id=1TvqSCFAFz3ZXXuJhaavKBlMyoRO67DMt\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(54, \'Ketan Kamat\', \'https://drive.google.com/uc?id=1r5dNCWSDgQbcIcUffPLCBaRPQwPf9sLi\', 9, NULL, NULL, NULL, 3, NULL, NULL),
(55, \'kushal kamat\', \'https://drive.google.com/uc?id=1szkXy-TWZTAkSNAiNVKTW2dLxvWNY3NE\', 3, NULL, NULL, NULL, 1, NULL, NULL),
(56, \'Lakshmish Baliga\', \'https://drive.google.com/uc?id=1oxNi9s8CVV6qrJCfls44777mflHh5RRi\', 3, NULL, NULL, NULL, 2, NULL, NULL),
(57, \'Laxmish  Mallya\', \'https://drive.google.com/uc?id=1scSRq7zkWgf80eU_l7LWvXF_sl4lgFXJ\', 9, NULL, NULL, NULL, 3, NULL, NULL),
(58, \'Lokesh pai\', \'https://drive.google.com/uc?id=1i28S3VbOv51bvbVtXzpeaONCRdaoZ7zl\', 3, NULL, NULL, NULL, 1, NULL, NULL),
(59, \'Mahesh Shenoy\', \'https://drive.google.com/uc?id=1bpzEIZ3kYDPgvVfI2NVAPyhBU4wX9O3o\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(60, \'Mandar Mahale\', \'https://drive.google.com/uc?id=1uwuWV9y5cxOGZaZbN60iVXQ-PhSvcUJJ\', 3, NULL, NULL, NULL, 1, NULL, NULL),
(61, \'Manjunath  Kamath\', \'https://drive.google.com/uc?id=17Glbfsd25n1MqHBJe6mLVJNhv-9lBMWf\', 1, NULL, NULL, NULL, 3, NULL, 1),
(62, \'MAYUR PADIYAR\', \'https://drive.google.com/uc?id=1VXDUfWYfucVe5UWUwa1EcghO0nLMkELE\', 6, NULL, NULL, NULL, 3, NULL, NULL),
(63, \'Mayuresh Shenoy\', \'https://drive.google.com/uc?id=1silhmRkgpDpUSQ9OIObWwmmpeXdr-WU1\', 6, NULL, NULL, NULL, 3, NULL, NULL),
(64, \'MEHUL KAMATH\', \'https://drive.google.com/uc?id=1mL2N_iqXGROSfz7juoqWQ2ZfcYXGdE4V\', 4, NULL, NULL, NULL, 1, NULL, NULL),
(65, \'N Rajesh  Nayak\', \'https://drive.google.com/uc?id=1yj77pMfGYALMIQOdJZJF1msxPsd5BvPE\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(66, \'N Raveendra  Nayak \', \'https://drive.google.com/uc?id=1QXJFCAEAU5WUSswNgd5W8Npbmb7e1rZR\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(67, \'Nagesh  Pai\', \'https://drive.google.com/uc?id=1J5b2jspK5FShUYmlxVI878dv7SWmxTfF\', 2, NULL, NULL, NULL, 3, NULL, 1),
(68, \'Nandan Prabhu\', \'https://drive.google.com/uc?id=1oSD7vSZPYCmLCyZ0gn37IvLMnBySWoB5\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(69, \'Narendra Nayak\', \'https://drive.google.com/uc?id=1PynKoCfjhyE1YCPvExiIAGULszWQJAKj\', 6, NULL, NULL, NULL, 1, NULL, NULL),
(70, \'Naresh  Kamath\', \'https://drive.google.com/uc?id=1hdirXWL7MD8xsbDqVmUdO6C_JSZQFSeo\', 1, NULL, NULL, NULL, 3, NULL, NULL),
(71, \'Navneet Prabhu\', \'https://drive.google.com/uc?id=1odOJhiYlfPNMOra5C8wXm6OqXv3k2ztD\', 3, NULL, NULL, NULL, 1, NULL, NULL),
(72, \'Nishant Kamat\', \'https://drive.google.com/uc?id=1tvLDEChVEbh_idaRWa7SxXa9vZ5QIU23\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(73, \'Padmanabha  Pai \', \'https://drive.google.com/uc?id=1Xuc1osyZRZG0Vqd3_8tIr-M-yfAArdU8\', 5, NULL, NULL, NULL, 2, NULL, NULL),
(74, \'Prajwal Kamat\', \'https://drive.google.com/uc?id=1KN22bh5A3t3ilY4HaSVWpJcc-AlBx66x\', 7, NULL, NULL, NULL, 3, NULL, NULL),
(75, \'Prajwal Bhaktha\', \'https://drive.google.com/uc?id=1whWCGZYMp6ATCurnMI5Kuf0kzvAXZYl0\', 2, NULL, NULL, NULL, 3, NULL, 1),
(76, \'Pranav Pai\', \'https://drive.google.com/uc?id=1Qn1YJ6BENkj-F3fKY0TZDy51wWB91kth\', 2, NULL, NULL, NULL, 2, NULL, 1),
(77, \'PRASAD NAYAK\', \'https://drive.google.com/uc?id=1EzmW6m6VzHTE2iqP0-V-rLavB1PwFcLm\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(78, \'Prasad Shanbhag\', \'https://drive.google.com/uc?id=1DCV01qZAMiITgP9fyiSlqvy8o8DRrraL\', 7, NULL, NULL, NULL, 2, NULL, NULL),
(79, \'PRASAD BHANDARKAR\', \'https://drive.google.com/uc?id=164uxKpPpm7iWODr4LCysIPJAa2bHmj_b\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(80, \'Prasanna Kamat\', \'https://drive.google.com/uc?id=1YQqf-dh8SOl16Ghl9TZF5iCmsNNqIUZm\', 7, NULL, NULL, NULL, 3, NULL, NULL),
(81, \'Prashant Prabhu\', \'https://drive.google.com/uc?id=1LFs6_9HwJgutMMBkQhg_C-c68jEIMVEh\', 1, NULL, NULL, NULL, 3, NULL, NULL),
(82, \'Pratap  Nayak\', \'https://drive.google.com/uc?id=1heN0br6z2V7xauxrJhVqT7tFCkMaDF1g\', 9, NULL, NULL, NULL, 1, NULL, NULL),
(83, \'Prateek Prabhu\', \'https://drive.google.com/uc?id=14raOK-ouqQdELkQLmKayvn496bkYAFTj\', 6, NULL, NULL, NULL, 3, NULL, NULL),
(84, \'Pratik Prabhu\', \'https://drive.google.com/uc?id=1T6GNx82IcMLWoELK7Za0jDXWjKJp-9NW\', 3, NULL, NULL, NULL, 1, NULL, NULL),
(85, \'Pratik  Prabhu\', \'https://drive.google.com/uc?id=1_pmDvPgtVs1XPLCNxmbX04b2uLIr_koh\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(86, \'Pundalika Pai\', \'https://drive.google.com/uc?id=1kT79Y_rjipP2KjU3QVeQia0dGjODX1lY\', 1, NULL, NULL, NULL, 3, NULL, NULL),
(87, \'Pushkar Gaitonde\', \'https://drive.google.com/uc?id=1nNWEN39PI61ebfTbYjr_sqYCOOswbYoT\', 6, NULL, NULL, NULL, 1, NULL, NULL),
(88, \'Ragvendra Bhat\', \'https://drive.google.com/uc?id=1D5OJjialgTSU_DbE_TDnAx9G9iJ0kuzk\', 8, NULL, NULL, NULL, 1, NULL, NULL),
(89, \'Rahul Borkar\', \'https://drive.google.com/uc?id=1yMgLa_uk8WdWrQWPW6rtoWBsk9sVfH18\', 7, NULL, NULL, NULL, 1, NULL, NULL),
(90, \'Rahul Shanbhag\', \'https://drive.google.com/uc?id=1ta_IIY__u9Dp3UQADJaONfYZ5Vj_bA3A\', 7, NULL, NULL, NULL, 3, NULL, NULL),
(91, \'Rahul  Pai\', \'https://drive.google.com/uc?id=1oywVthNXA0IxsrRO34NhAcZhr3xyukqO\', 6, NULL, NULL, NULL, 2, NULL, NULL),
(92, \'Rajatha R\', \'https://drive.google.com/uc?id=1Dc983iTtqviMOdXeWKjCaLo5ZvYpOihU\', 2, NULL, NULL, NULL, 1, NULL, 1),
(93, \'RAJEEV KAMATH\', \'https://drive.google.com/uc?id=1u668RUEIhzA6jZMnwwVNrsEl7TjX-WFh\', 6, NULL, NULL, NULL, 3, NULL, NULL),
(94, \'Rakesh R Kamath\', \'https://drive.google.com/uc?id=1dbAvBdurHeKP83rvv6iBmopx9F7j4CQ_\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(95, \'Ramakrishna Kamath\', \'https://drive.google.com/uc?id=11A19ZfY_T_JUBXgYmp1p3kEAe3HvturK\', 8, NULL, NULL, NULL, 2, NULL, NULL),
(96, \'Ratish Pai\', \'https://drive.google.com/uc?id=1OVxJqk8vVGuxEhnJo4jPLEK3OHb_RPTc\', 2, NULL, NULL, NULL, 3, NULL, 1),
(97, \'Ratnakar Padiyar\', \'https://drive.google.com/uc?id=1EFpL5PokgkzKGyKm0iJZFW1-bRxJjCeG\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(98, \'Ravichandra Keshav Nayak Nayak\', \'https://drive.google.com/uc?id=1ITbMchUadczHJNkFgVXvvgdqEn9ju3qU\', 7, NULL, NULL, NULL, 3, NULL, NULL),
(99, \'Rohan Nayak\', \'https://drive.google.com/uc?id=1rWVVdR9NwBP68u2U4ShjkepK5k-9gN7p\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(100, \'Roshan Borkar\', \'https://drive.google.com/uc?id=1G6L-kvahJYbc48DPjmP6Uv2X4ewKqNT4\', 7, NULL, NULL, NULL, 3, NULL, NULL),
(101, \'Rushabh Mahale\', \'https://drive.google.com/uc?id=1uYWXXOFQ7nyWKzzy0dit7KipGahRRxPB\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(102, \'Sameer Shanbhag\', \'https://drive.google.com/uc?id=1v58UvylRSStONSL0O_Ixend-FzR0wYQA\', 4, NULL, NULL, NULL, 2, NULL, NULL),
(103, \'Sandeep Kamath\', \'https://drive.google.com/uc?id=1lktY7mBvfJVq-ZC5ipuRd8w0G-NVAW9a\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(104, \'Sandeep bhat\', \'https://drive.google.com/uc?id=1l_9Xjs9Zr97fYZo5lxAXkGRHKgGngh1v\', 1, NULL, NULL, NULL, 2, NULL, NULL),
(105, \'Sandeepa Nayak\', \'https://drive.google.com/uc?id=1VpgtRgLtzqU1ODeGS2tvn3umFOhADwoF\', 2, NULL, NULL, NULL, 3, NULL, NULL),
(106, \'Sandesh  Nayak\', \'https://drive.google.com/uc?id=1G5T32cMh24oS4M6PpXAZCf5PhlzPFIMr\', 1, NULL, NULL, NULL, 3, NULL, NULL),
(107, \'Santosh  Samanth \', \'https://drive.google.com/uc?id=1qvg3X6PuQU-DrZYf1U4_-lP_aHYtzBD2\', 7, NULL, NULL, NULL, 3, NULL, NULL),
(108, \'SATHISH KINI\', \'https://drive.google.com/uc?id=1MyYG6l2gkOOqdysuTScCVsPjJ_yZxx7W\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(109, \'Shailesh Prabhu\', \'https://drive.google.com/uc?id=1Px6anmtYDVsuUAvSePp3yit3DeGJr6pN\', 8, NULL, NULL, NULL, 2, NULL, NULL),
(110, \'Sharad Bhat\', \'https://drive.google.com/uc?id=1eX7hy3-BkJFkkkyqLixWb5s4Np8VTbOZ\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(111, \'Sharath prabhu Bully\', \'https://drive.google.com/uc?id=1PHf0m0mgdSVPpoeTVF34NWdUAaRb9THg\', 6, NULL, NULL, NULL, 3, NULL, NULL),
(112, \'SHASHIDHAR  BHAT\', \'https://drive.google.com/uc?id=1JJ79lD-9F7UaTX3l4ret1RK1glf5Ws1j\', 4, NULL, NULL, NULL, 1, NULL, NULL),
(113, \'Shashidhar  Pai\', \'https://drive.google.com/uc?id=1sIGYXZmag2CCUIBZwMulnf62Ptef60sQ\', 8, NULL, NULL, NULL, 1, NULL, NULL),
(114, \'Shivanand  Kamath\', \'https://drive.google.com/uc?id=1fucrCYtEEFCOWvNd9HCOcKXAc_LVvgoR\', 4, NULL, NULL, NULL, 3, NULL, NULL),
(115, \'Shreedhar  Shenoy \', \'https://drive.google.com/uc?id=1LIFsKG6qCK-D34MnohZyGgc62DZYB07H\', 9, NULL, NULL, NULL, 2, NULL, NULL),
(116, \'Shreenath Shenoy\', \'https://drive.google.com/uc?id=1Vhug_ni2gADLRVmL5y8fIUW9KaYRZZGa\', 3, NULL, NULL, NULL, 3, NULL, NULL),
(117, \'SHREYAS SHENOY\', \'https://drive.google.com/uc?id=1FCyPzVyARhX4P2RQxQL8voQ2f_qO-3g3\', 7, NULL, NULL, NULL, 3, NULL, NULL),
(118, \'Shridhar Mudlagiri\', \'https://drive.google.com/uc?id=18ce4SkhVMDe9sIZzifECNZ5iPPVH_j2l\', 7, NULL, NULL, NULL, 3, NULL, NULL),
(119, \'Siddhesh Pai\', \'https://drive.google.com/uc?id=1GHe6MfQBFXvKyysFrDQQak2WKhU_CGce\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(120, \'Siddhesh Pai\', \'https://drive.google.com/uc?id=1iv8UhIHnm5P0qvZVyWtTZ3sDjrf0rStm\', 6, NULL, NULL, NULL, 1, NULL, NULL),
(121, \'Sidhesh Ramani\', \'https://drive.google.com/uc?id=19vvocadcZIILLw-YQj0pIbjhaAgqF2NN\', 6, NULL, NULL, NULL, 1, NULL, NULL),
(122, \'Soumit Pikle\', \'https://drive.google.com/uc?id=1qAICKKdGiz5H1ixRaxqdp8p1qzvcgrMm\', 6, NULL, NULL, NULL, 3, NULL, NULL),
(123, \'Sourab Bhaktha\', \'https://drive.google.com/uc?id=1oxThOUKelWCJv92QZp6Nk0POh6iDghny\', 6, NULL, NULL, NULL, 3, NULL, NULL),
(124, \'Srinivas Pai BH\', \'https://drive.google.com/uc?id=1TgomhQh4UHi3S1OMbKsd4qnpRTK0fRpJ\', 2, NULL, NULL, NULL, 3, NULL, NULL),
(125, \'Sunit Shenoy\', \'https://drive.google.com/uc?id=1Cp2tv1Ak4o39F_Q3h_TJOCaleO9Oz3uT\', 2, NULL, NULL, NULL, 1, NULL, NULL),
(126, \'Surendra Pai\', \'https://drive.google.com/uc?id=1b8frhAiqAPmByK8NgcGesEOc9GAJIxAT\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(127, \'TUSHAR  TENDULKAR\', \'https://drive.google.com/uc?id=1MW41bb1r4SJjfil4z1FWaNUrzDX78KDY\', 6, NULL, NULL, NULL, 3, NULL, NULL),
(128, \'Umesh  Prabhu \', \'https://drive.google.com/uc?id=1p4ntsrbNSfiHcQQQODZOMI5Un85MwZDM\', 3, NULL, NULL, NULL, 3, NULL, NULL),
(129, \'vaibhav kamat\', \'https://drive.google.com/uc?id=1zUmaZivAwqlMBS3Af2gF3_avzG5u5Z5N\', 3, NULL, NULL, NULL, 3, NULL, NULL),
(130, \'Varun Shenoy\', \'https://drive.google.com/uc?id=1YMIJuTmcN1g6_1E9Q2psxBk8bSq52THJ\', 7, NULL, NULL, NULL, 2, NULL, NULL),
(131, \'Varun Mahale \', \'https://drive.google.com/uc?id=1AnQrR6IIyqru7exeg2ABVYGCzLS_wAHh\', 9, NULL, NULL, NULL, 1, NULL, NULL),
(132, \'Vasanth Nayak\', \'https://drive.google.com/uc?id=1TaxHsu4JArzJt04fPcTOPaH3yuzYXuxa\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(133, \'veerendra nayak\', \'https://drive.google.com/uc?id=13ZGexhvYpR1hDPfxBN6K7jVNI3qtQ6GO\', 7, NULL, NULL, NULL, 3, NULL, NULL),
(134, \'Venkatesh (Venky) Pai\', \'https://drive.google.com/uc?id=1P0-I9SgzJFZ5U2240V5eGO_n-JNlC8yU\', 9, NULL, NULL, NULL, 3, NULL, NULL),
(135, \'Vighnesh  Bhat\', \'https://drive.google.com/uc?id=1TqcuWO3d1oUYM1iEkCfy5Idj6kwvI3lU\', 2, NULL, NULL, NULL, 3, NULL, NULL),
(136, \'Vignesh Nayak\', \'https://drive.google.com/uc?id=1zjKMiPrP4eNVOX-kqj5OiL6a7UCAXDFH\', 3, NULL, NULL, NULL, 3, NULL, NULL),
(137, \'Vinay Barde\', \'https://drive.google.com/uc?id=1NHK8ohcjgx8cxXflRX2jMc47aSAcH-Hx\', 3, NULL, NULL, NULL, 3, NULL, NULL),
(138, \'VINAY PRABHU\', \'https://drive.google.com/uc?id=1h2yo4ULCHg9BViyHr4BO3S96oWwELHLB\', 7, NULL, NULL, NULL, 1, NULL, NULL),
(139, \'Vinayak Pai\', \'https://drive.google.com/uc?id=1wLe5IOMsPcvm-N01xGOOLh5EHU0DlZkL\', 8, NULL, NULL, NULL, 3, NULL, NULL),
(140, \'Vinod Nayak\', \'https://drive.google.com/uc?id=1aIsxOGpgAuVmPgcJAKtV-q5_cgiK21Nf\', 2, NULL, NULL, NULL, 3, NULL, NULL),
(141, \'Vivek Nayak\', \'https://drive.google.com/uc?id=1sEDT-o7cXsF1P2WosCHnQnPaDE3ghOW4\', 5, NULL, NULL, NULL, 3, NULL, NULL),
(142, \'Vivek Prabhu\', \'https://drive.google.com/uc?id=1VRCf-p7Ga7MIMTxsT2vcCYj-oZZToVqn\', 4, NULL, NULL, NULL, 1, NULL, NULL),
(143, \'Yogesh Prabhu\', \'https://drive.google.com/uc?id=1wGVUqxyDnOO17Te_u5LN3xyLXRvg9uxC\', 9, NULL, NULL, NULL, 1, NULL, NULL),
(144, \'Yogish  Pai\', \'https://drive.google.com/uc?id=1DDv-CliNYA-jj-PsdpLWCG2u6sTilxsB\', 5, NULL, NULL, NULL, 3, NULL, NULL)');
    }
}
